name: Deploy to Vercel

on:
  push:
    paths:
      - 'vercel-mock/**'  # Only trigger on changes in the vercel-mock directory
      - '.github/workflows/vercel-deploy.yml'  # Trigger on changes to the workflow file itself
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Vercel CLI
        run: npm ci -g vercel

      - name: Link to the Correct Vercel Project
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd vercel-mock
          vercel link --token $VERCEL_TOKEN --project ${{ secrets.VERCEL_PROJECT_ID }} --yes

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd vercel-mock
          vercel --prod --token $VERCEL_TOKEN --confirm
